//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::asset_rgb121::Entity as AssetRgb121;
pub use super::asset_rgb20::Entity as AssetRgb20;
pub use super::asset_transfer::Entity as AssetTransfer;
pub use super::batch_transfer::Entity as BatchTransfer;
pub use super::coloring::Entity as Coloring;
pub use super::transfer::Entity as Transfer;
pub use super::txo::Entity as Txo;
