//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::asset_rgb20::Entity as AssetRgb20;
pub use super::asset_rgb25::Entity as AssetRgb25;
pub use super::asset_transfer::Entity as AssetTransfer;
pub use super::batch_transfer::Entity as BatchTransfer;
pub use super::coloring::Entity as Coloring;
pub use super::consignment_endpoint::Entity as ConsignmentEndpoint;
pub use super::transfer::Entity as Transfer;
pub use super::transfer_consignment_endpoint::Entity as TransferConsignmentEndpoint;
pub use super::txo::Entity as Txo;
pub use super::wallet_transaction::Entity as WalletTransaction;
