//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "transfer_consignment_endpoint"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub idx: i64,
    pub transfer_idx: i64,
    pub consignment_endpoint_idx: i64,
    pub used: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Idx,
    TransferIdx,
    ConsignmentEndpointIdx,
    Used,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Idx,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ConsignmentEndpoint,
    Transfer,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Idx => ColumnType::BigInteger.def(),
            Self::TransferIdx => ColumnType::BigInteger.def(),
            Self::ConsignmentEndpointIdx => ColumnType::BigInteger.def(),
            Self::Used => ColumnType::Boolean.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ConsignmentEndpoint => Entity::belongs_to(super::consignment_endpoint::Entity)
                .from(Column::ConsignmentEndpointIdx)
                .to(super::consignment_endpoint::Column::Idx)
                .into(),
            Self::Transfer => Entity::belongs_to(super::transfer::Entity)
                .from(Column::TransferIdx)
                .to(super::transfer::Column::Idx)
                .into(),
        }
    }
}

impl Related<super::consignment_endpoint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConsignmentEndpoint.def()
    }
}

impl Related<super::transfer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transfer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
