FROM ghcr.io/grunch/rgb-proxy-server:0.1.0

# change consignment.post json-rpc method to return null
RUN sed -i '/consignment.post/{n;s/Promise<boolean>/Promise<void>/;}' \
        src/controllers/api.ts \
    && LINE=$(grep -Fn 'Promise<void>' src/controllers/api.ts |cut -d: -f1) \
    && echo "line: $LINE" \
    && sed -i "$((LINE+1)),+34d" src/controllers/api.ts


# rebuild app
RUN npm run build
