FROM ghcr.io/grunch/rgb-proxy-server:0.2.0

# change protocol version
RUN sed -i 's/const PROTOCOL_VERSION = "0.2";/const PROTOCOL_VERSION = "0.1";/' src/controllers/api.ts


# rebuild app
RUN npm run build
